spring:
  application:
    name: external.gateway
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
  base-url: ${MERCADOPAGO_BASE_URL:https://api.mercadopago.com}
